name: "Setup Node, PNPM and Prisma Client"
description: "Helper action to setup Node, PNPM and Prisma"
runs:
  using: "composite"
  steps:
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v6

    - name: "Setup Node"
      uses: actions/setup-node@v7
      with:
        version: '24'
        cache: 'pnpm'

    - name: "Install dependencies"
      run: pnpm install
      shell: bash

    - name: "Generate Prisma Client"
      run: pnpm run db:generate
      shell: bash