name: "Setup Bun and Prisma Client"
description: "Helper action to setup Bun and Prisma"
runs:
  using: "composite"
  steps:
    - name: "Setup Bun"
      uses: oven-sh/setup-bun@v2

    - name: "Install dependencies"
      run: bun install 
      shell: bash

    - name: "Generate Prisma Client"
      run: bun run db:generate
      shell: bash